import type { Socket } from "bun";
import type { ChatMode } from "#wow/client";
import type { CreatureInfo, NoticeEvent } from "#wow/client-extras";
import type { Arc4 } from "#wow/crypto/arc4";
import type { EntityStore } from "#wow/entity-store";
import type { FriendStore } from "#wow/friend-store";
import type { GuildStore } from "#wow/guild-store";
import type { IgnoreStore } from "#wow/ignore-store";
import type { PacketTap } from "#wow/packet-trace";
import type { PartyStore } from "#wow/party-store";
import type { ChatMessage as RawChatMessage } from "#wow/protocol/chat";
import type { AccumulatorBuffer, OpcodeDispatch } from "#wow/protocol/world";
import type { RemoteMotion } from "#wow/remote-motion";
import type { WorldEvents } from "#wow/world-events";

export type WorldConn = {
  socket?: Socket;
  dispatch: OpcodeDispatch;
  buf: AccumulatorBuffer;
  arc4?: Arc4;
  startTime: number;
  pendingHeader?: { size: number; opcode: number };
  dispatchingOpcode?: number;
  nameCache: Map<number, string>;
  pendingMessages: Map<number, RawChatMessage[]>;
  channels: string[];
  lastChatMode: ChatMode;
  lastWhisperFrom?: string;
  selfName: string;
  selfClass?: string;
  selfGuidLow: number;
  selfGuidHigh: number;
  partyMembers: Map<string, { guidLow: number; guidHigh: number }>;
  party: PartyStore;
  entityStore: EntityStore;
  pendingEntityDeliveries: (() => void)[];
  remoteMotion: RemoteMotion;
  creatureNameCache: Map<number, string>;
  gameObjectNameCache: Map<number, string>;
  pendingNameQueries: Set<string>;
  friendStore: FriendStore;
  ignoreStore: IgnoreStore;
  guildStore: GuildStore;
  guildId: number;
  pendingRequest: "group" | "duel" | null;
  duelArbiter: bigint;
  events: WorldEvents;
  pendingNotices: NoticeEvent[];
  trace?: PacketTap;
  creatureInfoCache: Map<number, CreatureInfo>;
};
