import type { AreaOpcodes } from "#wow/areas/contract";

export const QUESTS_OPCODES = {
  owns: [
    "CMSG_QUESTGIVER_STATUS_QUERY",
    "CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY",
    "SMSG_QUESTGIVER_STATUS_MULTIPLE",
    "CMSG_QUEST_POI_QUERY",
    "SMSG_QUEST_POI_QUERY_RESPONSE",
    "CMSG_NPC_TEXT_QUERY",
    "SMSG_NPC_TEXT_UPDATE",
    "SMSG_GOSSIP_POI",
    "CMSG_QUESTGIVER_HELLO",
    "CMSG_QUESTGIVER_QUEST_AUTOLAUNCH",
    "CMSG_QUESTLOG_SWAP_QUEST",
    "CMSG_QUERY_QUESTS_COMPLETED",
    "SMSG_QUERY_QUESTS_COMPLETED_RESPONSE",
    "CMSG_PUSHQUESTTOPARTY",
    "MSG_QUEST_PUSH_RESULT",
    "SMSG_QUEST_CONFIRM_ACCEPT",
    "CMSG_QUEST_CONFIRM_ACCEPT",
    "SMSG_QUEST_FORCE_REMOVE",
  ],
  uses: ["SMSG_QUESTGIVER_STATUS"],
  stubs: [],
  dead: ["SMSG_QUEST_FORCE_REMOVE"],
  unseen: ["SMSG_GOSSIP_POI"],
} as const satisfies AreaOpcodes;
