import type { AreaOpcodes } from "#wow/areas/contract";

export const CHARTERS_OPCODES = {
  owns: [
    "CMSG_PETITION_SHOWLIST",
    "SMSG_PETITION_SHOWLIST",
    "CMSG_PETITION_BUY",
    "CMSG_PETITION_SHOW_SIGNATURES",
    "SMSG_PETITION_SHOW_SIGNATURES",
    "CMSG_PETITION_SIGN",
    "SMSG_PETITION_SIGN_RESULTS",
    "MSG_PETITION_DECLINE",
    "CMSG_OFFER_PETITION",
    "CMSG_TURN_IN_PETITION",
    "SMSG_TURN_IN_PETITION_RESULTS",
    "CMSG_PETITION_QUERY",
    "SMSG_PETITION_QUERY_RESPONSE",
    "MSG_PETITION_RENAME",
  ],
  uses: [
    "SMSG_ITEM_PUSH_RESULT",
    "SMSG_BUY_FAILED",
    "SMSG_GUILD_COMMAND_RESULT",
    "SMSG_ARENA_TEAM_COMMAND_RESULT",
    "SMSG_INVENTORY_CHANGE_FAILURE",
  ],
  stubs: [],
  dead: [],
  unseen: ["MSG_PETITION_DECLINE"],
} as const satisfies AreaOpcodes;
