import type { AreaOpcodes } from "#wow/areas/contract";

export const AUCTION_OPCODES = {
  owns: [
    "MSG_AUCTION_HELLO",
    "CMSG_AUCTION_SELL_ITEM",
    "CMSG_AUCTION_REMOVE_ITEM",
    "CMSG_AUCTION_LIST_ITEMS",
    "CMSG_AUCTION_LIST_OWNER_ITEMS",
    "CMSG_AUCTION_PLACE_BID",
    "SMSG_AUCTION_COMMAND_RESULT",
    "SMSG_AUCTION_LIST_RESULT",
    "SMSG_AUCTION_OWNER_LIST_RESULT",
    "SMSG_AUCTION_BIDDER_NOTIFICATION",
    "SMSG_AUCTION_OWNER_NOTIFICATION",
    "CMSG_AUCTION_LIST_BIDDER_ITEMS",
    "SMSG_AUCTION_BIDDER_LIST_RESULT",
    "SMSG_AUCTION_REMOVED_NOTIFICATION",
    "CMSG_AUCTION_LIST_PENDING_SALES",
    "SMSG_AUCTION_LIST_PENDING_SALES",
  ],
  uses: [],
  stubs: [
    ["SMSG_AUCTION_OWNER_NOTIFICATION", "Auction sold"],
    ["SMSG_AUCTION_BIDDER_NOTIFICATION", "Auction outbid"],
    ["SMSG_AUCTION_COMMAND_RESULT", "Auction result"],
  ],
  dead: ["SMSG_AUCTION_REMOVED_NOTIFICATION"],
  unseen: [],
} as const satisfies AreaOpcodes;
