import type { AreaOpcodes } from "#wow/areas/contract";

export const INSTANCES_OPCODES = {
  owns: [
    "MSG_SET_DUNGEON_DIFFICULTY",
    "MSG_SET_RAID_DIFFICULTY",
    "SMSG_INSTANCE_DIFFICULTY",
    "SMSG_UPDATE_INSTANCE_OWNERSHIP",
    "SMSG_UPDATE_LAST_INSTANCE",
    "SMSG_RAID_INSTANCE_MESSAGE",
    "SMSG_RAID_GROUP_ONLY",
    "SMSG_CORPSE_NOT_IN_INSTANCE",
    "CMSG_REQUEST_RAID_INFO",
    "SMSG_RAID_INSTANCE_INFO",
    "SMSG_INSTANCE_SAVE_CREATED",
    "SMSG_INSTANCE_LOCK_WARNING_QUERY",
    "CMSG_INSTANCE_LOCK_RESPONSE",
    "CMSG_SET_SAVED_INSTANCE_EXTEND",
    "CMSG_RESET_INSTANCES",
    "SMSG_INSTANCE_RESET",
    "SMSG_INSTANCE_RESET_FAILED",
    "SMSG_RESET_FAILED_NOTIFY",
    "SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT",
  ],
  uses: [],
  stubs: [],
  dead: [],
  unseen: [
    "MSG_SET_RAID_DIFFICULTY",
    "SMSG_UPDATE_LAST_INSTANCE",
    "SMSG_RAID_INSTANCE_MESSAGE",
    "SMSG_CORPSE_NOT_IN_INSTANCE",
  ],
} as const satisfies AreaOpcodes;
