import type { AreaOpcodes } from "#wow/areas/contract";

export const WINTERGRASP_OPCODES = {
  owns: [
    "SMSG_BATTLEFIELD_MGR_ENTRY_INVITE",
    "CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE",
    "SMSG_BATTLEFIELD_MGR_ENTERED",
    "SMSG_BATTLEFIELD_MGR_QUEUE_INVITE",
    "CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE",
    "SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE",
    "SMSG_BATTLEFIELD_MGR_EJECT_PENDING",
    "SMSG_BATTLEFIELD_MGR_EJECTED",
    "CMSG_BATTLEFIELD_MGR_EXIT_REQUEST",
    "SMSG_BATTLEFIELD_MGR_STATE_CHANGE",
    "CMSG_HEARTH_AND_RESURRECT",
    "SMSG_DESTRUCTIBLE_BUILDING_DAMAGE",
  ],
  uses: [],
  stubs: [],
  dead: [
    "SMSG_BATTLEFIELD_MGR_EJECT_PENDING",
    "SMSG_BATTLEFIELD_MGR_STATE_CHANGE",
  ],
  unseen: [
    "SMSG_BATTLEFIELD_MGR_ENTRY_INVITE",
    "SMSG_BATTLEFIELD_MGR_ENTERED",
    "SMSG_DESTRUCTIBLE_BUILDING_DAMAGE",
  ],
} as const satisfies AreaOpcodes;
