export const nerdFontsVersion = "3.4.0";

export const nerdClasses = {
  bag: { class: "nf-md-bag_personal", code: "U+F0E10" },
  boss: { class: "nf-md-skull_crossbones", code: "U+F0BC6" },
  buff: { class: "nf-md-chevron_double_up", code: "U+F013F" },
  cast: { class: "nf-md-magic_staff", code: "U+F1844" },
  clock: { class: "nf-md-clock_outline", code: "U+F0150" },
  combat: { class: "nf-md-sword_cross", code: "U+F0787" },
  compassE: { class: "nf-md-arrow_right", code: "U+F0054" },
  compassN: { class: "nf-md-arrow_up", code: "U+F005D" },
  compassNE: { class: "nf-md-arrow_top_right", code: "U+F005C" },
  compassNW: { class: "nf-md-arrow_top_left", code: "U+F005B" },
  compassS: { class: "nf-md-arrow_down", code: "U+F0045" },
  compassSE: { class: "nf-md-arrow_bottom_right", code: "U+F0043" },
  compassSW: { class: "nf-md-arrow_bottom_left", code: "U+F0042" },
  compassW: { class: "nf-md-arrow_left", code: "U+F004D" },
  cooldown: { class: "nf-md-timer_sand", code: "U+F051F" },
  copper: { class: "nf-md-alpha_c_circle", code: "U+F0BF2" },
  corpse: { class: "nf-md-grave_stone", code: "U+F0BA2" },
  damageIn: { class: "nf-md-arrow_down_bold_circle", code: "U+F0047" },
  damageOut: { class: "nf-md-arrow_up_bold_circle", code: "U+F005F" },
  dead: { class: "nf-md-skull_outline", code: "U+F0BC8" },
  death: { class: "nf-md-skull", code: "U+F068C" },
  debuff: { class: "nf-md-chevron_double_down", code: "U+F013C" },
  elite: { class: "nf-md-crown", code: "U+F01A5" },
  energy: { class: "nf-md-lightning_bolt", code: "U+F140B" },
  error: { class: "nf-md-close_octagon", code: "U+F015C" },
  facingE: { class: "nf-md-arrow_right_thick", code: "U+F0055" },
  facingN: { class: "nf-md-arrow_up_thick", code: "U+F005E" },
  facingNE: { class: "nf-md-arrow_top_right_thick", code: "U+F09C6" },
  facingNW: { class: "nf-md-arrow_top_left_thick", code: "U+F09C4" },
  facingS: { class: "nf-md-arrow_down_thick", code: "U+F0046" },
  facingSE: { class: "nf-md-arrow_bottom_right_thick", code: "U+F09BA" },
  facingSW: { class: "nf-md-arrow_bottom_left_thick", code: "U+F09B8" },
  facingW: { class: "nf-md-arrow_left_thick", code: "U+F004E" },
  flee: { class: "nf-md-run_fast", code: "U+F046E" },
  flightMaster: { class: "nf-md-bird", code: "U+F15C6" },
  friendly: { class: "nf-md-account_check", code: "U+F0008" },
  gameObject: { class: "nf-md-rhombus_outline", code: "U+F070C" },
  ghost: { class: "nf-md-ghost", code: "U+F02A0" },
  gold: { class: "nf-md-alpha_g_circle", code: "U+F0BFE" },
  guild: { class: "nf-md-shield_crown", code: "U+F18BC" },
  health: { class: "nf-fa-heart", code: "U+F004" },
  hostile: { class: "nf-md-account_alert", code: "U+F0005" },
  idle: { class: "nf-md-sleep", code: "U+F04B2" },
  item: { class: "nf-md-cube_outline", code: "U+F01A7" },
  jevDecision: { class: "nf-md-head_lightbulb", code: "U+F1344" },
  kill: { class: "nf-md-target_account", code: "U+F0BD0" },
  levelUp: { class: "nf-md-chevron_triple_up", code: "U+F0DBC" },
  loot: { class: "nf-md-sack", code: "U+F0D2E" },
  lootable: { class: "nf-md-treasure_chest", code: "U+F0726" },
  mana: { class: "nf-md-water", code: "U+F058C" },
  mapPin: { class: "nf-md-map_marker", code: "U+F034E" },
  neutral: { class: "nf-md-account_outline", code: "U+F0013" },
  party: { class: "nf-md-account_group", code: "U+F0849" },
  partyChat: { class: "nf-md-forum", code: "U+F028C" },
  questAvailable: { class: "nf-md-exclamation_thick", code: "U+F1238" },
  questComplete: { class: "nf-md-help", code: "U+F02D6" },
  questDone: { class: "nf-md-progress_check", code: "U+F0995" },
  questFailed: { class: "nf-md-progress_close", code: "U+F110A" },
  questgiver: { class: "nf-md-account_voice", code: "U+F05CB" },
  questInProgress: { class: "nf-md-progress_question", code: "U+F1522" },
  questLog: { class: "nf-md-script_text_outline", code: "U+F0BC3" },
  rage: { class: "nf-md-fire", code: "U+F0238" },
  rangeRing: { class: "nf-md-radius_outline", code: "U+F0CC1" },
  rare: { class: "nf-md-diamond_stone", code: "U+F01C8" },
  route: { class: "nf-md-map_marker_path", code: "U+F0D20" },
  runDone: { class: "nf-md-check_circle", code: "U+F05E0" },
  runFailed: { class: "nf-md-close_circle", code: "U+F0159" },
  runRunning: { class: "nf-md-progress_clock", code: "U+F0996" },
  say: { class: "nf-md-message_text", code: "U+F0369" },
  self: { class: "nf-md-crosshairs_gps", code: "U+F01A4" },
  shield: { class: "nf-fa-shield", code: "U+F132" },
  silver: { class: "nf-md-alpha_s_circle", code: "U+F0C22" },
  spell: { class: "nf-md-auto_fix", code: "U+F0068" },
  spiritHealer: { class: "nf-md-hands_pray", code: "U+F0579" },
  sword: { class: "nf-md-sword", code: "U+F04E5" },
  system: { class: "nf-md-cog", code: "U+F0493" },
  target: { class: "nf-md-target", code: "U+F04FE" },
  trainer: { class: "nf-md-school", code: "U+F0474" },
  vendor: { class: "nf-md-cart", code: "U+F0110" },
  warning: { class: "nf-md-alert", code: "U+F0026" },
  waypoint: { class: "nf-md-map_marker_outline", code: "U+F07D9" },
  whisper: { class: "nf-md-email_outline", code: "U+F01F0" },
  xp: { class: "nf-md-star_four_points", code: "U+F0AE2" },
} as const;

export type GlyphName = keyof typeof nerdClasses;

export const glyphSetNames = ["nerd", "unicode", "ascii"] as const;

export type GlyphSetName = (typeof glyphSetNames)[number];

export type GlyphSet = Readonly<Record<GlyphName, string>>;

export const nerd = {
  bag: "\u{f0e10}",
  boss: "\u{f0bc6}",
  buff: "\u{f013f}",
  cast: "\u{f1844}",
  clock: "\u{f0150}",
  combat: "\u{f0787}",
  compassE: "\u{f0054}",
  compassN: "\u{f005d}",
  compassNE: "\u{f005c}",
  compassNW: "\u{f005b}",
  compassS: "\u{f0045}",
  compassSE: "\u{f0043}",
  compassSW: "\u{f0042}",
  compassW: "\u{f004d}",
  cooldown: "\u{f051f}",
  copper: "\u{f0bf2}",
  corpse: "\u{f0ba2}",
  damageIn: "\u{f0047}",
  damageOut: "\u{f005f}",
  dead: "\u{f0bc8}",
  death: "\u{f068c}",
  debuff: "\u{f013c}",
  elite: "\u{f01a5}",
  energy: "\u{f140b}",
  error: "\u{f015c}",
  facingE: "\u{f0055}",
  facingN: "\u{f005e}",
  facingNE: "\u{f09c6}",
  facingNW: "\u{f09c4}",
  facingS: "\u{f0046}",
  facingSE: "\u{f09ba}",
  facingSW: "\u{f09b8}",
  facingW: "\u{f004e}",
  flee: "\u{f046e}",
  flightMaster: "\u{f15c6}",
  friendly: "\u{f0008}",
  gameObject: "\u{f070c}",
  ghost: "\u{f02a0}",
  gold: "\u{f0bfe}",
  guild: "\u{f18bc}",
  health: "\u{f004}",
  hostile: "\u{f0005}",
  idle: "\u{f04b2}",
  item: "\u{f01a7}",
  jevDecision: "\u{f1344}",
  kill: "\u{f0bd0}",
  levelUp: "\u{f0dbc}",
  loot: "\u{f0d2e}",
  lootable: "\u{f0726}",
  mana: "\u{f058c}",
  mapPin: "\u{f034e}",
  neutral: "\u{f0013}",
  party: "\u{f0849}",
  partyChat: "\u{f028c}",
  questAvailable: "\u{f1238}",
  questComplete: "\u{f02d6}",
  questDone: "\u{f0995}",
  questFailed: "\u{f110a}",
  questgiver: "\u{f05cb}",
  questInProgress: "\u{f1522}",
  questLog: "\u{f0bc3}",
  rage: "\u{f0238}",
  rangeRing: "\u{f0cc1}",
  rare: "\u{f01c8}",
  route: "\u{f0d20}",
  runDone: "\u{f05e0}",
  runFailed: "\u{f0159}",
  runRunning: "\u{f0996}",
  say: "\u{f0369}",
  self: "\u{f01a4}",
  shield: "\u{f132}",
  silver: "\u{f0c22}",
  spell: "\u{f0068}",
  spiritHealer: "\u{f0579}",
  sword: "\u{f04e5}",
  system: "\u{f0493}",
  target: "\u{f04fe}",
  trainer: "\u{f0474}",
  vendor: "\u{f0110}",
  warning: "\u{f0026}",
  waypoint: "\u{f07d9}",
  whisper: "\u{f01f0}",
  xp: "\u{f0ae2}",
} as const satisfies GlyphSet;

export const unicode = {
  bag: "\u{2294}",
  boss: "\u{265a}",
  buff: "\u{21c8}",
  cast: "\u{2726}",
  clock: "\u{25f7}",
  combat: "\u{2694}",
  compassE: "\u{2192}",
  compassN: "\u{2191}",
  compassNE: "\u{2197}",
  compassNW: "\u{2196}",
  compassS: "\u{2193}",
  compassSE: "\u{2198}",
  compassSW: "\u{2199}",
  compassW: "\u{2190}",
  cooldown: "\u{25f4}",
  copper: "\u{24d2}",
  corpse: "\u{271a}",
  damageIn: "\u{25be}",
  damageOut: "\u{25b4}",
  dead: "\u{2613}",
  death: "\u{2620}",
  debuff: "\u{21ca}",
  elite: "\u{265b}",
  energy: "\u{3df}",
  error: "\u{2298}",
  facingE: "\u{25ba}",
  facingN: "\u{25b2}",
  facingNE: "\u{25e5}",
  facingNW: "\u{25e4}",
  facingS: "\u{25bc}",
  facingSE: "\u{25e2}",
  facingSW: "\u{25e3}",
  facingW: "\u{25c4}",
  flee: "\u{21c7}",
  flightMaster: "\u{2303}",
  friendly: "\u{25cf}",
  gameObject: "\u{25a3}",
  ghost: "\u{25cc}",
  gold: "\u{24d6}",
  guild: "\u{265c}",
  health: "\u{2661}",
  hostile: "\u{2715}",
  idle: "\u{2219}",
  item: "\u{25c6}",
  jevDecision: "\u{25ca}",
  kill: "\u{2021}",
  levelUp: "\u{21d1}",
  loot: "\u{229b}",
  lootable: "\u{25c8}",
  mana: "\u{2248}",
  mapPin: "\u{2691}",
  neutral: "\u{25cb}",
  party: "\u{25d2}",
  partyChat: "\u{25eb}",
  questAvailable: "!",
  questComplete: "?",
  questDone: "\u{2713}",
  questFailed: "\u{2717}",
  questgiver: "\u{a1}",
  questInProgress: "\u{25d0}",
  questLog: "\u{a7}",
  rage: "\u{2206}",
  rangeRing: "\u{25ef}",
  rare: "\u{25c7}",
  route: "\u{2504}",
  runDone: "\u{221a}",
  runFailed: "\u{2718}",
  runRunning: "\u{27f3}",
  say: "\u{bb}",
  self: "\u{2316}",
  shield: "\u{26e8}",
  silver: "\u{24e2}",
  spell: "\u{2727}",
  spiritHealer: "\u{263c}",
  sword: "\u{2020}",
  system: "\u{203b}",
  target: "\u{25ce}",
  trainer: "\u{270e}",
  vendor: "\u{a4}",
  warning: "\u{26a0}",
  waypoint: "\u{25e6}",
  whisper: "\u{2709}",
  xp: "\u{2736}",
} as const satisfies GlyphSet;

export const ascii = {
  bag: "b",
  boss: "B",
  buff: "+",
  cast: "~",
  clock: "@",
  combat: "#",
  compassE: ">",
  compassN: "^",
  compassNE: "/",
  compassNW: "\u{5c}",
  compassS: "v",
  compassSE: "\u{5c}",
  compassSW: "/",
  compassW: "<",
  cooldown: ":",
  copper: "c",
  corpse: "C",
  damageIn: "v",
  damageOut: "^",
  dead: "%",
  death: "D",
  debuff: "-",
  elite: "E",
  energy: "e",
  error: "E",
  facingE: ">",
  facingN: "^",
  facingNE: "/",
  facingNW: "\u{5c}",
  facingS: "v",
  facingSE: "\u{5c}",
  facingSW: "/",
  facingW: "<",
  flee: "f",
  flightMaster: "F",
  friendly: "+",
  gameObject: "o",
  ghost: "&",
  gold: "g",
  guild: "G",
  health: "h",
  hostile: "x",
  idle: "z",
  item: "i",
  jevDecision: "j",
  kill: "k",
  levelUp: "U",
  loot: "L",
  lootable: "$",
  mana: "m",
  mapPin: "M",
  neutral: "o",
  party: "p",
  partyChat: "P",
  questAvailable: "!",
  questComplete: "?",
  questDone: "v",
  questFailed: "x",
  questgiver: "Q",
  questInProgress: "~",
  questLog: "Q",
  rage: "r",
  rangeRing: "O",
  rare: "R",
  route: ".",
  runDone: "+",
  runFailed: "x",
  runRunning: "*",
  say: ">",
  self: "@",
  shield: "]",
  silver: "s",
  spell: "&",
  spiritHealer: "A",
  sword: "/",
  system: "#",
  target: "*",
  trainer: "T",
  vendor: "V",
  warning: "!",
  waypoint: ",",
  whisper: "w",
  xp: "X",
} as const satisfies GlyphSet;

export const glyphSets: Readonly<Record<GlyphSetName, GlyphSet>> = {
  ascii,
  nerd,
  unicode,
};

export const isGlyphSetName = (
  value: string | undefined,
): value is GlyphSetName => glyphSetNames.some((name) => name === value);

export const resolveGlyphSet = (
  flag: string | undefined,
  env: string | undefined,
  warn: (message: string) => void,
): GlyphSetName => {
  const [source, value] =
    flag === undefined ? ["PEON_GLYPHS", env] : ["--glyphs", flag];
  if (value === undefined || value === "") return "nerd";
  if (isGlyphSetName(value)) return value;
  warn(
    `${source}=${value} is not one of ${glyphSetNames.join("|")}; using nerd`,
  );
  return "nerd";
};

export const glyphNamesByChar = (
  set: GlyphSet,
): ReadonlyMap<string, readonly GlyphName[]> =>
  Object.entries(set).reduce((map, [name, glyph]) => {
    map.set(glyph, [...(map.get(glyph) ?? []), name as GlyphName]);
    return map;
  }, new Map<string, GlyphName[]>());

const nerdByChar = glyphNamesByChar(nerd);

export const glyphName = (char: string): GlyphName | undefined =>
  nerdByChar.get(char)?.[0];

export const tagNerdGlyphs = (screen: string): string =>
  [...screen]
    .map((char) => {
      const name = nerdByChar.get(char)?.[0];
      return name === undefined ? char : `<${name}>`;
    })
    .join("");
